services:
  backend:
    command: ["sleep", "infinity"]
    volumes:
      - ./backend:/app
      - ~/.ssh:/root/.ssh:ro
    working_dir: /app

  db:
    ports:
      - "5432:5432"
    networks:
      - internal
      - web
